// <auto-generated />
using System;
using DAOs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace DAOs.Migrations
{
    [DbContext(typeof(OverlutDbContext))]
    [Migration("20260324133216_AddRoleIdToRescueTeam")]
    partial class AddRoleIdToRescueTeam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.OverlutEntiy.AttachmentMission", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AttachmentID");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MissionId")
                        .HasColumnType("int")
                        .HasColumnName("MissionID");

                    b.HasKey("AttachmentId");

                    b.HasIndex("MissionId");

                    b.ToTable("AttachmentMission", (string)null);
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.AttachmentRescue", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AttachmentID");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RescueRequestId")
                        .HasColumnType("int")
                        .HasColumnName("RescueRequestID");

                    b.HasKey("AttachmentId")
                        .HasName("PK_RescueRequestAttachments");

                    b.HasIndex("RescueRequestId");

                    b.ToTable("AttachmentRescue", (string)null);
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__Categori__8517B2E0DB728485")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.InventoryTransaction", b =>
                {
                    b.Property<int>("TxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TxID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TxId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<int>("MissionId")
                        .HasColumnType("int")
                        .HasColumnName("MissionID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TxType")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.HasKey("TxId");

                    b.HasIndex("MissionId");

                    b.HasIndex("WarehouseId", "ProductId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.MissionLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<int>("MissionId")
                        .HasColumnType("int")
                        .HasColumnName("MissionID");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ChangedByUserID");

                    b.Property<string>("OldRescueMissions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("LogId", "MissionId");

                    b.HasIndex("MissionId");

                    b.ToTable("MissionLogs");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IPAddress");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("RefreshTokenId")
                        .HasName("PK__RefreshT__F5845E392455FC9A");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Token" }, "UQ__RefreshT__1EB4F8175D3536C7")
                        .IsUnique()
                        .HasFilter("[Token] IS NOT NULL");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueMembersRole", b =>
                {
                    b.Property<int>("RescueMembersRoleId")
                        .HasColumnType("int")
                        .HasColumnName("RescueMembersRoleID");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RescueMembersRoleId");

                    b.HasIndex(new[] { "RoleName" }, "UQ_RescueMembersRoles_RollName")
                        .IsUnique();

                    b.ToTable("RescueMembersRoles");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueMission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MissionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("CoordinatorUserId")
                        .HasColumnType("int")
                        .HasColumnName("CoordinatorUserID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RescueRequestId")
                        .HasColumnType("int")
                        .HasColumnName("RescueRequestID");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    b.HasKey("MissionId");

                    b.HasIndex("CoordinatorUserId");

                    b.HasIndex("RescueRequestId");

                    b.HasIndex("StatusId");

                    b.ToTable("RescueMissions");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueMissionsStatus", b =>
                {
                    b.Property<int>("RescueMissionsStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RescueMissionsStatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RescueMissionsStatusId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RescueMissionsStatusId");

                    b.HasIndex(new[] { "StatusName" }, "UQ_RescueMissionsStatus_StatusName")
                        .IsUnique();

                    b.ToTable("RescueMissionsStatus", (string)null);
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueRequest", b =>
                {
                    b.Property<int>("RescueRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RescueRequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RescueRequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("LocationText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PeopleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UrgencyLevel")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserReqId")
                        .HasColumnType("int")
                        .HasColumnName("UserReqID");

                    b.HasKey("RescueRequestId");

                    b.HasIndex("RequestType");

                    b.HasIndex("Status");

                    b.HasIndex("UrgencyLevel");

                    b.HasIndex("UserReqId");

                    b.ToTable("RescueRequests");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueRequestLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<int>("RescueRequestId")
                        .HasColumnType("int")
                        .HasColumnName("RescueRequestID");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ChangedByUserID");

                    b.Property<string>("OldRescueRequests")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("LogId", "RescueRequestId")
                        .HasName("PK_RescueRequestLog");

                    b.HasIndex("RescueRequestId");

                    b.ToTable("RescueRequestLogs");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueRequestsStatus", b =>
                {
                    b.Property<int>("RescueRequestsStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RescueRequestsStatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RescueRequestsStatusId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RescueRequestsStatusId");

                    b.ToTable("RescueRequestsStatus", (string)null);
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueRequestsType", b =>
                {
                    b.Property<int>("RescueRequestsTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RescueRequestsTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RescueRequestsTypeId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RescueRequestsTypeId");

                    b.ToTable("RescueRequestsTypes");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueTeam", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<double?>("AssemblyLatitude")
                        .HasColumnType("float");

                    b.Property<string>("AssemblyLocationText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("AssemblyLongitude")
                        .HasColumnType("float");

                    b.Property<string>("AssemblyNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TeamId");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.ToTable("RescueTeams");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueTeamMember", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("AssignedByUserID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("MemberId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TeamId");

                    b.HasIndex(new[] { "UserId", "TeamId" }, "UQ_RescueTeamMembers_User_Team");

                    b.ToTable("RescueTeamMembers");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueTeamsStatus", b =>
                {
                    b.Property<int>("RescueTeamsStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RescueTeamsStatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RescueTeamsStatusId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RescueTeamsStatusId");

                    b.ToTable("RescueTeamsStatus", (string)null);
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "RoleName" }, "UQ_Roles_RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 6,
                            RoleName = "Volunteer"
                        });
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.UrgencyLevel", b =>
                {
                    b.Property<int>("UrgencyLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UrgencyLevelID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrgencyLevelId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UrgencyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UrgencyLevelId")
                        .HasName("PK_UrgencyLevel");

                    b.ToTable("UrgencyLevels");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IdentifyId")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("IdentifyID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VehicleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<string>("VehicleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VehicleType");

                    b.HasIndex(new[] { "VehicleCode" }, "UQ_Vehicles_VehicleCode")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VehicleAssignment", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("int")
                        .HasColumnName("MissionID");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("VehicleID");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MissionId", "VehicleId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleAssignments");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VehiclesStatus", b =>
                {
                    b.Property<int>("VehiclesStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VehiclesStatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehiclesStatusId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehiclesStatusId");

                    b.ToTable("VehiclesStatus", (string)null);
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VehiclesType", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VehicleTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleTypeId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehicleTypeId");

                    b.ToTable("VehiclesTypes");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VolunteerOffer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OfferID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferId"));

                    b.Property<string>("AssetCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("AvailableFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AvailableTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("CurrentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double?>("DropoffLatitude")
                        .HasColumnType("float");

                    b.Property<string>("DropoffLocationText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("DropoffLongitude")
                        .HasColumnType("float");

                    b.Property<bool>("IsReturnRequired")
                        .HasColumnType("bit");

                    b.Property<string>("OfferName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("OfferTypeId")
                        .HasColumnType("int")
                        .HasColumnName("OfferTypeID");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("OfferId");

                    b.HasIndex("OfferTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("VolunteerOffers");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VolunteerOfferAssignment", b =>
                {
                    b.Property<int>("OfferAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OfferAssignmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferAssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("AssignedByManagerId")
                        .HasColumnType("int")
                        .HasColumnName("AssignedByManagerID");

                    b.Property<int?>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("OfferId")
                        .HasColumnType("int")
                        .HasColumnName("OfferID");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReturnConditionNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    b.HasKey("OfferAssignmentId");

                    b.HasIndex("AssignedByManagerId");

                    b.HasIndex("OfferId");

                    b.HasIndex("TeamId");

                    b.ToTable("VolunteerOfferAssignments");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VolunteerOfferType", b =>
                {
                    b.Property<int>("OfferTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OfferTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferTypeId"));

                    b.Property<bool>("IsTypicallyReturnable")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OfferTypeId");

                    b.HasIndex(new[] { "TypeName" }, "UQ_VolunteerOfferTypes_TypeName")
                        .IsUnique();

                    b.ToTable("VolunteerOfferTypes");

                    b.HasData(
                        new
                        {
                            OfferTypeId = 1,
                            IsTypicallyReturnable = false,
                            TypeName = "Food"
                        },
                        new
                        {
                            OfferTypeId = 2,
                            IsTypicallyReturnable = true,
                            TypeName = "LifeJacket"
                        },
                        new
                        {
                            OfferTypeId = 3,
                            IsTypicallyReturnable = true,
                            TypeName = "Boat"
                        },
                        new
                        {
                            OfferTypeId = 4,
                            IsTypicallyReturnable = false,
                            TypeName = "MedicalSupplies"
                        },
                        new
                        {
                            OfferTypeId = 5,
                            IsTypicallyReturnable = true,
                            TypeName = "RescueEquipment"
                        },
                        new
                        {
                            OfferTypeId = 6,
                            IsTypicallyReturnable = false,
                            TypeName = "Other"
                        });
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VolunteerProfile", b =>
                {
                    b.Property<int>("VolunteerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VolunteerProfileID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteerProfileId"));

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("VolunteerProfileId");

                    b.HasIndex("ApprovedByManagerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("VolunteerProfiles");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VolunteerSkill", b =>
                {
                    b.Property<int>("VolunteerSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VolunteerSkillID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteerSkillId"));

                    b.Property<int>("SkillTypeId")
                        .HasColumnType("int")
                        .HasColumnName("SkillTypeID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("VolunteerProfileId")
                        .HasColumnType("int");

                    b.HasKey("VolunteerSkillId");

                    b.HasIndex("SkillTypeId");

                    b.HasIndex("VolunteerProfileId");

                    b.HasIndex(new[] { "UserId", "SkillTypeId" }, "UQ_VolunteerSkills_User_Skill")
                        .IsUnique();

                    b.ToTable("VolunteerSkills");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VolunteerSkillType", b =>
                {
                    b.Property<int>("SkillTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SkillTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillTypeId"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillTypeId");

                    b.HasIndex(new[] { "SkillName" }, "UQ_VolunteerSkillTypes_SkillName")
                        .IsUnique();

                    b.ToTable("VolunteerSkillTypes");

                    b.HasData(
                        new
                        {
                            SkillTypeId = 1,
                            SkillName = "MedicalSupport"
                        },
                        new
                        {
                            SkillTypeId = 2,
                            SkillName = "DirectRescuer"
                        },
                        new
                        {
                            SkillTypeId = 3,
                            SkillName = "LogisticsSupport"
                        },
                        new
                        {
                            SkillTypeId = 4,
                            SkillName = "BoatOperator"
                        });
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("WarehouseId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.WarehouseStock", b =>
                {
                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<decimal>("CurrentQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("WarehouseId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("WarehouseStock", (string)null);
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.AttachmentMission", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.RescueMission", "Mission")
                        .WithMany("AttachmentMissions")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AttachmentMission_RescueMissions");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.AttachmentRescue", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.RescueRequest", "RescueRequest")
                        .WithMany("AttachmentRescues")
                        .HasForeignKey("RescueRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AttachmentRescue_RescueRequests");

                    b.Navigation("RescueRequest");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.InventoryTransaction", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.RescueMission", "Mission")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("MissionId")
                        .IsRequired()
                        .HasConstraintName("FK_InventoryTransactions_RescueMissions");

                    b.HasOne("BusinessObject.OverlutEntiy.WarehouseStock", "WarehouseStock")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("WarehouseId", "ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_InventoryTransactions_Products");

                    b.Navigation("Mission");

                    b.Navigation("WarehouseStock");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.MissionLog", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.RescueMission", "Mission")
                        .WithMany("MissionLogs")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MissionLogs_RescueMissions");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.Product", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RefreshToken", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__RefreshTo__UserI__2D27B809");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueMission", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.User", "CoordinatorUser")
                        .WithMany("RescueMissions")
                        .HasForeignKey("CoordinatorUserId")
                        .IsRequired()
                        .HasConstraintName("FK_RescueMissions_Users");

                    b.HasOne("BusinessObject.OverlutEntiy.RescueRequest", "RescueRequest")
                        .WithMany("RescueMissions")
                        .HasForeignKey("RescueRequestId")
                        .IsRequired()
                        .HasConstraintName("FK_RescueMissions_RescueRequests");

                    b.HasOne("BusinessObject.OverlutEntiy.RescueMissionsStatus", "Status")
                        .WithMany("RescueMissions")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_RescueMissions_RescueMissionsStatus");

                    b.Navigation("CoordinatorUser");

                    b.Navigation("RescueRequest");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueRequest", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.RescueRequestsType", "RequestTypeNavigation")
                        .WithMany("RescueRequests")
                        .HasForeignKey("RequestType")
                        .IsRequired()
                        .HasConstraintName("FK_RescueRequests_RescueRequestsTypes");

                    b.HasOne("BusinessObject.OverlutEntiy.RescueRequestsStatus", "StatusNavigation")
                        .WithMany("RescueRequests")
                        .HasForeignKey("Status")
                        .IsRequired()
                        .HasConstraintName("FK_RescueRequests_RescueRequestsStatus");

                    b.HasOne("BusinessObject.OverlutEntiy.UrgencyLevel", "UrgencyLevelNavigation")
                        .WithMany("RescueRequests")
                        .HasForeignKey("UrgencyLevel")
                        .HasConstraintName("FK_RescueRequests_UrgencyLevels");

                    b.HasOne("BusinessObject.OverlutEntiy.User", "UserReq")
                        .WithMany("RescueRequests")
                        .HasForeignKey("UserReqId")
                        .HasConstraintName("FK_RescueRequests_UserReqID");

                    b.Navigation("RequestTypeNavigation");

                    b.Navigation("StatusNavigation");

                    b.Navigation("UrgencyLevelNavigation");

                    b.Navigation("UserReq");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueRequestLog", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.RescueRequest", "RescueRequest")
                        .WithMany("RescueRequestLogs")
                        .HasForeignKey("RescueRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReqStatusHistory_RescueRequests");

                    b.Navigation("RescueRequest");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueTeam", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.RescueMembersRole", "Role")
                        .WithMany("RescueTeams")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_RescueTeams_RescueMembersRoles");

                    b.HasOne("BusinessObject.OverlutEntiy.RescueTeamsStatus", "Status")
                        .WithMany("RescueTeams")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_RescueTeams_RescueTeamsStatus");

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueTeamMember", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .HasConstraintName("FK_RescueTeamMembers_AssignedByUser");

                    b.HasOne("BusinessObject.OverlutEntiy.RescueMembersRole", "Role")
                        .WithMany("RescueTeamMembers")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_RescueTeamMembers_RescueMembersRoles");

                    b.HasOne("BusinessObject.OverlutEntiy.RescueTeam", "Team")
                        .WithMany("RescueTeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TeamMembers_Team");

                    b.HasOne("BusinessObject.OverlutEntiy.User", "User")
                        .WithMany("RescueTeamMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_RescueTeamMembers_Users");

                    b.Navigation("AssignedByUser");

                    b.Navigation("Role");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.User", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.Vehicle", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.VehiclesStatus", "Status")
                        .WithMany("Vehicles")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Vehicles_VehiclesStatus");

                    b.HasOne("BusinessObject.OverlutEntiy.VehiclesType", "VehicleTypeNavigation")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleType")
                        .IsRequired()
                        .HasConstraintName("FK_Vehicles_VehiclesTypes");

                    b.Navigation("Status");

                    b.Navigation("VehicleTypeNavigation");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VehicleAssignment", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.RescueMission", "Mission")
                        .WithMany("VehicleAssignments")
                        .HasForeignKey("MissionId")
                        .IsRequired()
                        .HasConstraintName("FK_VehicleAssignments_RescueMissions");

                    b.HasOne("BusinessObject.OverlutEntiy.Vehicle", "Vehicle")
                        .WithMany("VehicleAssignments")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_VehicleAssignments_Vehicle");

                    b.Navigation("Mission");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VolunteerOffer", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.VolunteerOfferType", "OfferType")
                        .WithMany("VolunteerOffers")
                        .HasForeignKey("OfferTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_VolunteerOffers_OfferTypes");

                    b.HasOne("BusinessObject.OverlutEntiy.User", "User")
                        .WithMany("VolunteerOffers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VolunteerOffers_Users");

                    b.Navigation("OfferType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VolunteerOfferAssignment", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.User", "AssignedByManager")
                        .WithMany()
                        .HasForeignKey("AssignedByManagerId")
                        .IsRequired()
                        .HasConstraintName("FK_VolunteerOfferAssignments_Managers");

                    b.HasOne("BusinessObject.OverlutEntiy.VolunteerOffer", "Offer")
                        .WithMany("Assignments")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VolunteerOfferAssignments_Offers");

                    b.HasOne("BusinessObject.OverlutEntiy.RescueTeam", "Team")
                        .WithMany("VolunteerOfferAssignments")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK_VolunteerOfferAssignments_Teams");

                    b.Navigation("AssignedByManager");

                    b.Navigation("Offer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VolunteerProfile", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.User", "ApprovedByManager")
                        .WithMany()
                        .HasForeignKey("ApprovedByManagerId")
                        .HasConstraintName("FK_VolunteerProfiles_Managers");

                    b.HasOne("BusinessObject.OverlutEntiy.User", "User")
                        .WithOne("VolunteerProfile")
                        .HasForeignKey("BusinessObject.OverlutEntiy.VolunteerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VolunteerProfiles_Users");

                    b.Navigation("ApprovedByManager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VolunteerSkill", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.VolunteerSkillType", "SkillType")
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VolunteerSkills_SkillTypes");

                    b.HasOne("BusinessObject.OverlutEntiy.User", "User")
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VolunteerSkills_Users");

                    b.HasOne("BusinessObject.OverlutEntiy.VolunteerProfile", null)
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("VolunteerProfileId");

                    b.Navigation("SkillType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.WarehouseStock", b =>
                {
                    b.HasOne("BusinessObject.OverlutEntiy.Product", "Product")
                        .WithMany("WarehouseStocks")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Stock_Products");

                    b.HasOne("BusinessObject.OverlutEntiy.Warehouse", "Warehouse")
                        .WithMany("WarehouseStocks")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_Stock_Warehouses");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.Product", b =>
                {
                    b.Navigation("WarehouseStocks");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueMembersRole", b =>
                {
                    b.Navigation("RescueTeamMembers");

                    b.Navigation("RescueTeams");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueMission", b =>
                {
                    b.Navigation("AttachmentMissions");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("MissionLogs");

                    b.Navigation("VehicleAssignments");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueMissionsStatus", b =>
                {
                    b.Navigation("RescueMissions");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueRequest", b =>
                {
                    b.Navigation("AttachmentRescues");

                    b.Navigation("RescueMissions");

                    b.Navigation("RescueRequestLogs");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueRequestsStatus", b =>
                {
                    b.Navigation("RescueRequests");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueRequestsType", b =>
                {
                    b.Navigation("RescueRequests");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueTeam", b =>
                {
                    b.Navigation("RescueTeamMembers");

                    b.Navigation("VolunteerOfferAssignments");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.RescueTeamsStatus", b =>
                {
                    b.Navigation("RescueTeams");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.UrgencyLevel", b =>
                {
                    b.Navigation("RescueRequests");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("RescueMissions");

                    b.Navigation("RescueRequests");

                    b.Navigation("RescueTeamMembers");

                    b.Navigation("VolunteerOffers");

                    b.Navigation("VolunteerProfile");

                    b.Navigation("VolunteerSkills");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.Vehicle", b =>
                {
                    b.Navigation("VehicleAssignments");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VehiclesStatus", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VehiclesType", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VolunteerOffer", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VolunteerOfferType", b =>
                {
                    b.Navigation("VolunteerOffers");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VolunteerProfile", b =>
                {
                    b.Navigation("VolunteerSkills");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.VolunteerSkillType", b =>
                {
                    b.Navigation("VolunteerSkills");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.Warehouse", b =>
                {
                    b.Navigation("WarehouseStocks");
                });

            modelBuilder.Entity("BusinessObject.OverlutEntiy.WarehouseStock", b =>
                {
                    b.Navigation("InventoryTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
